### ISSUE TITLE
Is it possible to have links open to new tabs instead of having to go back each time?

### ISSUE THREAD

**Issue by tasmie** [acm-chil/acm-chil-website#42]
If I click on any of the SlidesLive links it takes me to the page instead of opening a new tab. https://www.chilconference.org/calendar.html#tab-preview

**Comment by tnaumann** [comment]
Sure, this involves adding `target="_blank"` to the `<a>` link. Can you let me know which links / pages you have in mind?

**Comment by tasmie** [comment]
Guidance page https://www.chilconference.org/calendar.html#tab-guidance
- [ ] Besides the Rocketchat one, the hyperlinks don't redirect to the pages 
- [ ] Would be nice if RC opened on another tab 

Prerecorded content page https://www.chilconference.org/calendar.html#tab-preview
- [ ] Instead of "Link" perhaps the text can say "View on Slideslive" since the video shows up when you click on the title and when you click on "Link" ? 
- [ ] Links should open to new tabs 

Thursday Schedule https://www.chilconference.org/calendar.html#tab-thu
- [ ] links should open tabs for both zoom and titles 
- [ ] Most right column should read "Q&A Session Link" or "Live Q&A" instead of just session link

Friday Schedule https://www.chilconference.org/calendar.html#tab-fri
- [ ] links should open tabs for both zoom and titles 
- [ ] Most right column should read "Q&A Session Link" or "Live Q&A" instead of just session link

Keynotes, Tutorials, Workshop and Doc Symp to open in new tabs as well, if it's not too much work.

**Comment by tnaumann** [comment]
@tasmie update most of these. For the last 4, I disagree re: opening titles to new tabs since those pages are internal to the site. Right now the semantic is that if it's opening a new site (e.g. SlidesLive or Zoom) it will open a new tab. The one exception to this is RocketChat since that will also open a new tab from the Guidance page even though it's embedded in our site. Let me know if you think this should be donee differently.

@corcra the first bullet appears to be an actual bug. I was digging around in component and I'm not sure why this isn't working, but can you take a look?

**Comment by tasmie** [comment]
@tnaumann that's fine with me! Opening a new tab for other sites is fine while leaving the internal pages is great.

**Comment by corcra** [comment]
Closing this as the main issue is solved, I've created #48 for this particular bug.
