### ISSUE TITLE
Label zoom rooms on Thurs+Friday schedule

### ISSUE THREAD

**Issue by tasmie** [acm-chil/acm-chil-website#72]
Something we should a little more clear are the zoom rooms. Instead of using "Zoom" or "Zoom (as above), could we use Zoom room number, i.e. "Zoom 1" ? They are listed in the minute by minute here: https://docs.google.com/spreadsheets/d/1BRCCVjyUiWGI2s8os8-F5gY4mB9U6f70j9XCs_yiX2w/edit#gid=452609008

**Comment by corcra** [comment]
It looks like Marzyeh already did this for Thursday yesterday (https://github.com/acm-chil/acm-chil-website/commit/305ff814493a6808749422dbf35386c1dcea4b60), but the numbering doesn't match what's in the spreadsheet (the tutorials are 1A, 1B, 1C instead of 1, 2, 3). 

I think this numbering system makes more sense so I will copy it for Friday (to address #74 also), but the spreadsheet should probably be updated. (I don't want to touch the spreadsheet in case I mess it up)
